### ISSUE TITLE
CSV to JSON test issues

### ISSUE THREAD

**Issue by JeniT** [w3c/csvw#664]
Following are issues from going through the JSON tests
- [x] test002 tests (non-normative) parsing
- [x] test003 tests (non-normative) parsing
- [ ] test006 doesn't test anything that hasn't already been tested
- [ ] test007 doesn't test anything that hasn't already been tested
- [x] test009 I have raised an issue #659 otherwise it's fine
- [ ] test010 doesn't test anything that hasn't already been tested
- [x] test019 tests (non-normative) CSV best practice (and somewhat confusingly is supposed to show a CSV file without a header line but references a CSV file that does have a header line)
- [x] test020 tests (non-normative) parsing
- [x] test021 tests (non-normative) parsing
- [x] test022 tests (non-normative) parsing
- [x] if we're going to have tests for `trim` there ought to be one for `trim=false`
- [x] test024 tests (non-normative) parsing
- [x] test025 tests (non-normative) parsing
- [x] test026 is exactly the same as test012
- [ ] test028 doesn't test anything that hasn't already been tested
- [x] the HTML summary of the tests doesn't highlight that a particular test should generate a warning
- [x] test047 has an `@id` property in the result object for the row that I don't think should be there - the invalid `aboutUrl` should be being ignored
- [x] test048 has the same property URL (the URL of the CSV file) for all the columns in the row which isn't right - the invalid `propertyUrl` should be being ignored
- [x] test049 has the same value (URL) (the URL of the CSV file) for all the generated properties, which isn't right - the invalid `valueUrl` should be being ignored
- [x] test050 tests (non-normative) parsing
- [x] test051 tests (non-normative) parsing
- [x] test052 tests (non-normative) parsing
- [x] test054 tests (non-normative) parsing
- [x] test055 tests (non-normative) parsing
- [x] test056 tests (non-normative) parsing
- [x] test057 tests (non-normative) parsing
- [x] test058 tests (non-normative) parsing
- [x] test098 says that it implicitly relies on `tree-ops.csv` but it doesn't because the metadata file doesn't reference any CSV file. It should raise an error rather than a warning because it's not valid for the `tables` property to be an empty array.
- [x] in test125, I think the value of the `latitude` cell in the 3rd row should be `null` which I think means that the `latitude` property in the JSON should be missing (this is the same result as for test126 but with an implicit `null` value)
- [x] test127 I have raised an issue #659 otherwise it's fine
- [x] test129 I have raised an issue #659 otherwise it's fine
- [x] test130 I have raised an issue #659 otherwise it's fine
- [x] test131 I have raised an issue #659 otherwise it's fine
- [x] test132 I have raised an issue #659 otherwise it's fine
- [x] test147 should be a negative test I believe, because the titles from the CSV and from the metadata don't match (case-sensitively) so there isn't schema compatibility
- [x] test148 should also be a negative test because there isn't schema compatibility
- [x] test153 should be a warning I think - I have raised an issue #661
- [x] test155 needs to be updated to use number format patterns in the `format` property, also the `decimal` values should be numbers rather than strings
- [x] test156 should be a warning I think - I have raised an issue #661
- [x] test157 needs to be updated to use number format patterns in the `format` property
- [x] test158 needs to be updated to use number format patterns in the `format` property, also the `decimal` and `decimal1` values should be numbers rather than strings (they are coming out very oddly)
- [x] test159 should be a warning I think - I have raised an issue #661
- [x] test160 needs to be updated to use number format patterns in the `format` property
- [x] test162 needs to be slightly updated to include a format that specifies the `groupChar`
- [x] test168 needs to be slightly updated to include a format that specifies the `groupChar`; also the `decimal` property in the output is currently a string when it should be a number
- [x] test170 needs to be slightly updated to include a format that specifies the `groupChar`; also the `decimal` property in the output is currently a string when it should be a number
- [x] test171 needs to be slightly updated to include a format that specifies the `groupChar`; also the `decimal` property in the output is currently a string when it should be a number
- [x] test184 should be a warning I think - I have raised an issue #661
- [x] test191 should be a warning I think - I have raised an issue #661
- [x] test195 the lengths for the binary types are wrong - they need to constrain the number of _bytes_ not the number of characters in the lexical representation. I believe that the base64Binary value has 19 bytes in it and the hexBinary value has 2 bytes in it.
- [x] test200 I don't think should be an error; I raised an issue #663
- [x] test247 the description is wrong

**Comment by iherman** [comment]
All the test cases related to #659 have been taken care in PR #665. Marked them as done in the current list.

**Comment by JeniT** [comment]
I've similarly marked as done issues that have been fixed in PRs.

**Comment by JeniT** [comment]
I think the remaining items here and in #667 need changes to the manifest file, which I'm wary of making given there are already some PRs that contain such changes and git doesn't merge CSV files well. @gkellogg I'm hoping you can pick them up when you've merged the PRs.

**Comment by gkellogg** [comment]
@JeniT is your thought that all tests you marked with non-normative should be removed? Should we keep them but use a different type to indicate they're optional, or something else?

**Comment by JeniT** [comment]
@gkellogg I think labelled as non-normative so that they can be filtered out by implementers if they want to. A separate column?

**Comment by gkellogg** [comment]
@JeniT regarding 'the HTML summary of the tests doesn't highlight that a particular test should generate a warning', many tests do have this in the comment. Warnings are explicitly looked for when the test type is `csvt:WarningValidationTest` which is described in the front matter as expecting warnings.

**Comment by gkellogg** [comment]
@JeniT, regarding test047, it is an "invalid" test, meaning that it's a negative validation test, but transformations are generated without using metadata, so it's just like metadata isn't found. A "negative" in the spreadsheet indicates that all tested variations should fail; "invalid" that just validation should fail.

**Comment by JeniT** [comment]
@gkellogg re the HTML summary - it would be a nice-to-have to have a visual indication of which of the conversion tests are also expected to generate warnings, but this is certainly low priority.

re test147 (I think you meant, rather than test047?) yep, you're right, that test is fine. test148 too. I've checked them off above.

I don't agree with your interpretation that processor continues as if there's no metadata though: I think they should still match the columns up by position and apply the metadata that they find (eg to provide datatypes). test147 and test148 don't expose that kind of behaviour though. Perhaps another test (or amending one of these) to expose this behaviour would be useful?

**Comment by gkellogg** [comment]
The syntax spec specifically uses table compatibility to be able to use the metadata, when starting with a CSV, so if starting with a CSV, and no compatible metadata is found it will use only embedded metadata.

Re-reading the starting with metadata, I can see your (and @JeniT's) point that processing should continue with the metadata anyway; I'll work that in.

**Comment by gkellogg** [comment]
@JeniT: regarding test125, I can't find anything that says that if a cell is required and empty that it's value becomes `null`; this is controlled using the `null` annotation. It does generate a cell error. Can you provide a reference to back this reasoning?

**Comment by JeniT** [comment]
@gkellogg The definition of `null` includes:

> If not specified, the default for the null property is the empty string "".

Since `null` is not specified, it defaults to the empty string. There is no default provided for the `latitude` column, so an empty string, and no separator. So when parsing the value of the cell we get to:

> if the string is the same as any one of the values of the column null annotation, then the resulting value is null.

The empty string is the same as the (default) `null` annotation value, so the value of the cell is null.

**Comment by gkellogg** [comment]
Okay, sure, that clarifies it. I'll work on that when I get some time.
